/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.thomaswilde.intellijborderpane.app;


import com.thomaswilde.icons.GlyphButton;
import com.thomaswilde.intellijborderpane.ApplicationMainNode;
import com.thomaswilde.intellijborderpane.BarPosition;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import javafx.application.Application;
import javafx.scene.Node;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Label;
import javafx.scene.control.Menu;
import javafx.scene.control.MenuBar;
import javafx.scene.control.MenuItem;
import javafx.scene.layout.BorderPane;
import javafx.stage.Stage;

public class App extends Application {

    private static Logger log = LoggerFactory.getLogger(App.class);

    public static void main(String[] args) {
        launch(args);
    }

    @Override
    public void start(Stage primaryStage){

        log.info("App Started");

        Application.setUserAgentStylesheet("darcula.css");

        Scene scene = new Scene(getAppFrame(), 800, 600);

        primaryStage.setScene(scene);
        primaryStage.show();
    }

    private Parent getAppFrame(){

        ApplicationMainNode applicationMainNode = new ApplicationMainNode();
        MenuItem projectMenuItem = new MenuItem("Project");

        projectMenuItem.setOnAction(event -> {
            applicationMainNode.addNewToolWindow(
                    "Project",
                    new BorderPane(new Label("Project Content")),
                    GlyphButton.getGlyphIconStyled(GlyphButton.EDIT),
                    BarPosition.LEFT_TOP,
                    (menuToggleButton) -> {});
        });

        MenuItem structureMenuItem = new MenuItem("Structure");

        structureMenuItem.setOnAction(event -> {
            applicationMainNode.addNewToolWindow(
                    "Structure",
                    new BorderPane(new Label("Structure Content")),
                    GlyphButton.getGlyphIconStyled(GlyphButton.EDIT),
                    BarPosition.LEFT_TOP,
                    (menuToggleButton) -> {});
        });

        Menu toolWindowsMenuItem = new Menu("Tool Windows");
        toolWindowsMenuItem.getItems().addAll(projectMenuItem, structureMenuItem);

        Menu viewMenu = new Menu("View");
        viewMenu.getItems().add(toolWindowsMenuItem);

        MenuBar menuBar = new MenuBar(viewMenu);

        BorderPane borderPane = new BorderPane();
        borderPane.setTop(menuBar);
        borderPane.setCenter(applicationMainNode);

        return borderPane;
    }


}
